name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      uses: srt32/hugo-action@master
    
    - name: Add CNAME
      run: "echo \"cyclofix.osm.be\" | sudo tee -a \"/home/runner/work/cyclofix-website/cyclofix-website/public/CNAME\""
      shell: bash
    
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: public
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SQUASH_HISTORY: true
