name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master

    - name: Build
      uses: srt32/hugo-action@master
    
    - name: List
      run: "ls \"/home/runner/work/cyclofix-website/cyclofix-website/public\""
      shell: bash
    
    - name: Add CNAME
      run: "echo \"cyclofix.osm.be\" > \"/home/runner/work/cyclofix-website/cyclofix-website/public/CNAME\""
      shell: bash
  
    - name: List
      run: "ls \"/home/runner/work/cyclofix-website/cyclofix-website/public\""
      shell: bash
    
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: public
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
