name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
    - name: List wd
      run: |
        echo "test" && ls -la /home/runner/work/cyclofix-website/cyclofix-website/themes/compose
    - uses: srt32/hugo-action@master

