name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: List wd
      run: |
        echo "test" && ls -la /home/runner/work/cyclofix-website/cyclofix-website/themes
    - uses: srt32/hugo-action@master

